### ISSUE TITLE
Update Ionic devDependency to latest stable release

### ISSUE THREAD

**Issue by raymens** [TbLtzk/Centaurus#50]
It's currently using an old beta release:
`"ionic": "driftyco/ionic-bower#1.0.0-beta.11"`
This should be changed to the latest stable
``"ionic": "driftyco/ionic-bower#1.1.1"``

Or maybe even use the Bower repository for this.
`"ionic": "1.1.1"`

**Update**: seems that using any other version than the current beta 11 will mess up the UI big time. Haven't checked out why yet.

~~**Update 2**: in tabs.html the class is:
`<ion-tabs class="tabs-icon-top">` but in the beta 11 version it's at the bottom. Is this intended? Changing the class to `"tabs-icon-bottom"` will put it back at the bottom (as in the beta) for v1.0.0. When using v1.1.1 there's no UI at all (except for a back button text).~~

**Update 3**: So it seems that the UI doesn't get messed up big time if v1.0.0 is used. The difference between beta 11 and v1 is that apparently v1 uses the default location for the location of the tabs. At the top for Android and bottom for iOS etc (http://ionicframework.com/docs/api/directive/ionTabs/). It's allowed to override this, so it's up to you to decide if you want to override it or don't...?

Using v1.1.1 does mess up the UI as nothing is visible anymore, but that's the next step to fix :)

**Comment by raymens** [comment]
![image](https://cloud.githubusercontent.com/assets/1369454/11825353/d9d17972-a37e-11e5-868a-bcd20fd7fd27.png)

Made it work on `ionic 1.1.1`. Looks like that now.

**Comment by TbLtzk** [comment]
Yes this is how it looked like, when I tried the update some weeks ago, but frankly I don't like the tabs on top (and the tab labels are missing). and I did not take the time to figure out how to put them back to bottom also for android.
Is there a specific flaw in 1.0.0#beta11 or something you miss, that is fixed in version 1.1.1.? Otherwise  I would prefer to stick to the current version or tweek the android look and feel closer to how it is now.

**Comment by TbLtzk** [comment]
Do you need it for windows support?

**Comment by raymens** [comment]
According to the docs you can override this default behavior. I'll check it out in the next few days.

Not sure if I need it for Windows. But I expect I can get it back at the bottom without too much hassle.

**Comment by TbLtzk** [comment]
yeah great, then of course I'll be glad to pull your changes. It really feels better to go on a stable and at the same time more recent version of ionic.

**Comment by raymens** [comment]
It has been moved to the bottom specifically for android. See #52 

![image](https://cloud.githubusercontent.com/assets/1369454/11836016/0847dc52-a3d8-11e5-9534-796fe47b09a1.png)

**Comment by TbLtzk** [comment]
* view title: I prefer centered. Especially when we introduce the side menu I would expect in on the top left. But in the meantime I don't mind to have the title left aligned.
* text of nav buttons: I would like to have them back there as well.

**Comment by raymens** [comment]
View title has been centered, but I can't seem to find anything about displaying the text of nav buttons.

**Comment by raymens** [comment]
So it seems I actually removed the text of the nav buttons by mistake. They're back now :)
There's something wrong with the buttons though. This happens when using 1.1.1, they're fine in 1.0.0. I'll keep you updated.
![image](https://cloud.githubusercontent.com/assets/1369454/11839223/6ecfa022-a3ec-11e5-83cb-26b82885525d.png)
