### ISSUE TITLE
Upgrade stellar-sdk

### ISSUE THREAD

**Issue by bartekn** [TbLtzk/Centaurus#74]
stellar-sdk `0.6.0` has better support for streaming. Please consider upgrading.

**Comment by bartekn** [comment]
Could you update to `0.6.2`? We changed the location of `stellar.toml` file.

**Comment by TbLtzk** [comment]
some minor adaption necessary for this to work

**Comment by TbLtzk** [comment]
solved by 632e12979eb23329ba23427532ae9b1d8d439616
