### ISSUE TITLE
Withdrawal Issue

### ISSUE THREAD

**Issue by glendiosanta** [TbLtzk/Centaurus#87]
Hi sir! I just want to ask why everytime I try to withdraw it says complete but it never shows up in my Bittrex wallet. Please help sir.

**Comment by TbLtzk** [comment]
You're probably not sending the correct destination tag

**Comment by jedmccaleb** [comment]
Tbltzk: maybe consider doing what stellarterm does and require a memo if you are sending to kraken or bitrex

**Comment by TbLtzk** [comment]
yeah, sounds helpful. You don't happen to have a list of addresses, where it should be mandatory?

**Comment by jedmccaleb** [comment]
Search for "kraken" in this file: https://github.com/irisli/stellarterm/blob/9c3e060953a47769db3e836bff00952abc68ab28/directory/directory.json

**Comment by glendiosanta** [comment]
Thank you for replying to my message. The problem has been solved. The
reason I didn't get my XLM last time because I didn't put any memo on. But,
I am glad you guys replied.

Thank you for your patience and kindness.
